wget -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" -qO public/branco.mp3 "https://upload.wikimedia.org/wikipedia/commons/9/91/White_noise.ogg"
wget -U "Mozilla/5.0" -qO public/rosa.mp3 "https://upload.wikimedia.org/wikipedia/commons/b/b3/Pink_noise.ogg"
wget -U "Mozilla/5.0" -qO public/marrom.mp3 "https://upload.wikimedia.org/wikipedia/commons/d/d7/Brown_noise.ogg"
wget -U "Mozilla/5.0" -qO public/chuva.mp3 "https://upload.wikimedia.org/wikipedia/commons/d/da/Rain_sound.ogg"
wget -U "Mozilla/5.0" -qO public/vento.mp3 "https://upload.wikimedia.org/wikipedia/commons/5/52/Wind_howling.ogg"
wget -U "Mozilla/5.0" -qO public/Lareira.mp3 "https://upload.wikimedia.org/wikipedia/commons/c/cd/Campfire_sound.ogg"
wget -U "Mozilla/5.0" -qO public/Agua.mp3 "https://upload.wikimedia.org/wikipedia/commons/f/fb/Stream_water.ogg"
wget -U "Mozilla/5.0" -qO public/Passaros.mp3 "https://upload.wikimedia.org/wikipedia/commons/a/a2/Birds_in_spring.ogg"
wget -U "Mozilla/5.0" -qO public/Natureza.mp3 "https://upload.wikimedia.org/wikipedia/commons/1/1b/Forest_background.ogg"
